'use strict';
/**
 * STRATUM — persistent shared-world server.
 *
 * TWO LAYERS, TWO RULES:
 *   PERSISTENT — the land. Player-placed tiles are owned absolutely and never reset.
 *                Nobody can overwrite anyone's tiles. No admins, no moderation queue.
 *   VOLATILE   — the provisions. Resource nodes and monsters respawn on timers. They are
 *                generated by the world, not authored by players, so resetting them costs
 *                nobody anything. See world.js.
 *
 * Zero dependencies: node:http + node:sqlite + a hand-rolled RFC 6455 WebSocket layer.
 */
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');
const T = require('./public/terrain.js');
const { World, ATTACK_RANGE } = require('./world.js');

const PORT = Number(process.env.PORT || 8090);
const PUB = path.join(__dirname, 'public');
const DATA = path.join(__dirname, 'data');
fs.mkdirSync(DATA, { recursive: true });
const DBFILE = process.env.STRATUM_DB || path.join(DATA, 'world.db');

const W = T.W, H = T.H, CHUNK = T.CHUNK;
const REACH = 6;
const COST = 1, RELEASE_COST = 0, ENERGY_MAX = 240, REGEN_MS = 80;
const VIEW_RADIUS = 2;
const MAPGRID = 256, MAPSTEP = W / MAPGRID;
const B64 = 'base64';
const PLAYER_HP = 100, BASE_ATK = 7;

// ---------- persistence ----------------------------------------------------
const db = new DatabaseSync(DBFILE);
db.exec(`
  PRAGMA journal_mode = WAL;
  PRAGMA synchronous = NORMAL;
  CREATE TABLE IF NOT EXISTS players(
    k TEXT PRIMARY KEY, name TEXT NOT NULL, hue INTEGER NOT NULL,
    created INTEGER NOT NULL, last INTEGER NOT NULL);
  CREATE TABLE IF NOT EXISTS player_state(
    k TEXT PRIMARY KEY, map INTEGER NOT NULL, x REAL NOT NULL, y REAL NOT NULL,
    hp INTEGER NOT NULL, kills INTEGER NOT NULL, inv TEXT NOT NULL);
`);

// migrate a pre-maps tiles table (tiles used to be keyed by x,y only)
(function migrateTiles() {
  const cols = db.prepare('PRAGMA table_info(tiles)').all();
  const hasMap = cols.some(c => c.name === 'map');
  if (cols.length && !hasMap) {
    db.exec('ALTER TABLE tiles RENAME TO tiles_old');
    console.log('[db] migrating tiles table to per-map schema…');
  }
  db.exec(`CREATE TABLE IF NOT EXISTS tiles(
    map INTEGER NOT NULL, x INTEGER NOT NULL, y INTEGER NOT NULL, m INTEGER NOT NULL,
    owner TEXT NOT NULL, ts INTEGER NOT NULL, PRIMARY KEY(map,x,y));
    CREATE INDEX IF NOT EXISTS tiles_owner ON tiles(owner);`);
  if (cols.length && !hasMap) {
    db.exec('INSERT OR IGNORE INTO tiles(map,x,y,m,owner,ts) SELECT 0,x,y,m,owner,ts FROM tiles_old; DROP TABLE tiles_old;');
  }
})();

/** authoritative in-memory land: "map:y*W+x" -> {m, owner} */
const tiles = new Map();
const density = new Map();               // mapId -> Uint8Array(MAPGRID^2)
function densFor(map) {
  let d = density.get(map);
  if (!d) { d = new Uint8Array(MAPGRID * MAPGRID); density.set(map, d); }
  return d;
}
(function loadTiles() {
  const rows = db.prepare('SELECT map, x, y, m, owner FROM tiles').all();
  const perMap = {};
  for (const r of rows) {
    const key = r.map + ':' + (r.y * W + r.x);
    tiles.set(key, { m: r.m, owner: r.owner, map: r.map, x: r.x, y: r.y });
    const d = densFor(r.map);
    const i = (((r.y / MAPSTEP) | 0) * MAPGRID) + ((r.x / MAPSTEP) | 0);
    if (d[i] < 255) d[i]++;
    perMap[r.map] = (perMap[r.map] || 0) + 1;
  }
  const total = W * H;
  console.log(`[world] ${rows.length} owned tiles restored across ${Object.keys(perMap).length} map(s)`);
  for (const m of T.MAPS) {
    const c = perMap[m.id] || 0;
    console.log(`[world]   #${m.id} ${m.name}: ${c} claimed (${((c / total) * 100).toFixed(4)}%)`);
  }
})();

const qTile = db.prepare('INSERT OR REPLACE INTO tiles(map,x,y,m,owner,ts) VALUES(?,?,?,?,?,?)');
const qDel = db.prepare('DELETE FROM tiles WHERE map=? AND x=? AND y=?');
const qPlay = db.prepare('INSERT OR REPLACE INTO players(k,name,hue,created,last) VALUES(?,?,?,?,?)');
const qPlayGet = db.prepare('SELECT name,hue FROM players WHERE k=?');
const qPlayCount = db.prepare('SELECT COUNT(*) n FROM players');
const qPlayLast = db.prepare('UPDATE players SET last=? WHERE k=?');
const qState = db.prepare('INSERT OR REPLACE INTO player_state(k,map,x,y,hp,kills,inv) VALUES(?,?,?,?,?,?,?)');
const qStateGet = db.prepare('SELECT * FROM player_state WHERE k=?');

const world = new World(db);

// ---------- static files ---------------------------------------------------
const MIME = {
  '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8', '.json': 'application/json',
  '.png': 'image/png', '.ico': 'image/x-icon', '.svg': 'image/svg+xml'
};

const server = http.createServer((req, res) => {
  const url = new URL(req.url, 'http://x');
  let p = decodeURIComponent(url.pathname);

  if (p === '/api/stats') {
    const bodies = {};
    for (const m of T.MAPS) {
      let c = 0;
      for (const t of tiles.values()) if (t.map === m.id) c++;
      bodies[m.id] = { name: m.name, claimed: c, pct: +((c / (W * H)) * 100).toFixed(5) };
    }
    const body = JSON.stringify({
      world: { w: W, h: H, tiles: W * H },
      maps: bodies,
      claimed: tiles.size,
      online: [...clients.values()].filter(c => c.ready).length,
      playersEver: qPlayCount.get().n,
      volatile: world.stats(),
      spawn: T.spawnPoint(0)
    }, null, 2);
    res.writeHead(200, { 'content-type': 'application/json', 'cache-control': 'no-store' });
    return res.end(body);
  }

  if (p === '/') p = '/index.html';
  const file = path.join(PUB, path.normalize(p));
  if (!file.startsWith(PUB)) { res.writeHead(403); return res.end('no'); }
  fs.readFile(file, (err, buf) => {
    if (err) { res.writeHead(404, { 'content-type': 'text/plain' }); return res.end('404'); }
    const ext = path.extname(file).toLowerCase();
    res.writeHead(200, {
      'content-type': MIME[ext] || 'application/octet-stream',
      'cache-control': (ext === '.html' || ext === '.js') ? 'no-store' : 'public, max-age=3600'
    });
    res.end(buf);
  });
});

// ---------- websocket ------------------------------------------------------
const GUID = '258EAFA5-E914-47DA-95CA-C5AB0DC85B11';
const clients = new Map();
let nextId = 1;

function wsEncode(str, opcode) {
  const payload = Buffer.from(str, 'utf8');
  const len = payload.length;
  let head;
  if (len < 126) { head = Buffer.alloc(2); head[1] = len; }
  else if (len < 65536) { head = Buffer.alloc(4); head[1] = 126; head.writeUInt16BE(len, 2); }
  else { head = Buffer.alloc(10); head[1] = 127; head.writeBigUInt64BE(BigInt(len), 2); }
  head[0] = 0x80 | (opcode === undefined ? 1 : opcode);
  return Buffer.concat([head, payload]);
}

server.on('upgrade', (req, socket) => {
  const key = req.headers['sec-websocket-key'];
  if (!key) { socket.destroy(); return; }
  socket.write(
    'HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\n' +
    'Sec-WebSocket-Accept: ' + crypto.createHash('sha1').update(key + GUID).digest(B64) + '\r\n\r\n'
  );
  socket.setNoDelay(true);

  const c = {
    id: nextId++, sock: socket, key: null, name: null, hue: 0, map: 0,
    x: 0, y: 0, hp: PLAYER_HP, maxHp: PLAYER_HP, kills: 0, atk: BASE_ATK,
    inv: { wood: 0, ore: 0, herb: 0, crystal: 0 },
    energy: ENERGY_MAX, subs: new Set(), sent: new Set(),
    ready: false, lastMove: Date.now(), dead: false,
    send(obj) {
      if (socket.destroyed) return;
      try { socket.write(wsEncode(JSON.stringify(obj))); } catch (e) {}
    }
  };
  clients.set(socket, c);

  let buf = Buffer.alloc(0);
  socket.on('data', (chunk) => {
    buf = Buffer.concat([buf, chunk]);
    for (;;) {
      if (buf.length < 2) return;
      const b0 = buf[0], b1 = buf[1];
      const op = b0 & 0x0f;
      const masked = (b1 & 0x80) !== 0;
      let len = b1 & 0x7f, off = 2;
      if (len === 126) { if (buf.length < 4) return; len = buf.readUInt16BE(2); off = 4; }
      else if (len === 127) { if (buf.length < 10) return; len = Number(buf.readBigUInt64BE(2)); off = 10; }
      let mask = null;
      if (masked) { if (buf.length < off + 4) return; mask = buf.subarray(off, off + 4); off += 4; }
      if (buf.length < off + len) return;
      let payload = Buffer.from(buf.subarray(off, off + len));
      buf = buf.subarray(off + len);
      if (mask) for (let i = 0; i < payload.length; i++) payload[i] ^= mask[i & 3];

      if (op === 0x8) { socket.destroy(); return; }
      if (op === 0x9) { try { socket.write(wsEncode(payload.toString('utf8'), 0xA)); } catch (e) {} continue; }
      if (op === 0xA) continue;
      if (op === 0x1) {
        let msg;
        try { msg = JSON.parse(payload.toString('utf8')); } catch (e) { continue; }
        try { onMessage(c, msg); } catch (e) { console.log('[err]', e.stack || e.message); }
      }
    }
  });
  socket.on('error', () => {});
  socket.on('close', () => { clients.delete(socket); console.log(`[net] ${c.name || '#' + c.id} left (${live()} online)`); });
  console.log(`[net] #${c.id} connected`);
});

function live() { return [...clients.values()].filter(c => c.ready).length; }
function ready() { return [...clients.values()].filter(c => c.ready); }
function subKey(map, cx, cy) { return map + ':' + cx + ':' + cy; }

function sendChunk(c, cx, cy) {
  const map = c.map;
  const x0 = cx * CHUNK, y0 = cy * CHUNK;
  const out = []; const owners = []; const oIdx = new Map();
  for (let j = 0; j < CHUNK; j++) {
    for (let i = 0; i < CHUNK; i++) {
      const t = tiles.get(map + ':' + ((y0 + j) * W + (x0 + i)));
      if (!t) continue;
      let oi = oIdx.get(t.owner);
      if (oi === undefined) { oi = owners.length; owners.push(t.owner); oIdx.set(t.owner, oi); }
      out.push(i, j, t.m, oi);
    }
  }
  const bytes = new Uint8Array(out.length);
  for (let i = 0; i < out.length; i++) bytes[i] = out[i] & 0xff;
  c.send({
    t: 'chunk', map, cx, cy, n: out.length / 4,
    d: Buffer.from(bytes).toString(B64), owners,
    nodes: world.nodesForChunk(map, cx, cy)
  });
}

function setView(c, tx, ty) {
  const ccx = T.chunkOf(tx), ccy = T.chunkOf(ty);
  const want = new Set();
  for (let dy = -VIEW_RADIUS; dy <= VIEW_RADIUS; dy++) {
    for (let dx = -VIEW_RADIUS; dx <= VIEW_RADIUS; dx++) {
      const cx = ccx + dx, cy = ccy + dy;
      if (cx < 0 || cy < 0 || cx * CHUNK >= W || cy * CHUNK >= H) continue;
      want.add(subKey(c.map, cx, cy));
    }
  }
  const fresh = [];
  for (const k of want) {
    if (!c.sent.has(k)) { c.sent.add(k); const p = k.split(':'); fresh.push([+p[1], +p[2]]); }
  }
  // forget subscriptions to other maps
  for (const k of [...c.sent]) if (!k.startsWith(c.map + ':')) c.sent.delete(k);
  c.subs = want;
  for (const f of fresh) sendChunk(c, f[0], f[1]);
}

function broadcastTile(map, cx, cy, x, y, m, owner) {
  const k = subKey(map, cx, cy);
  for (const c of clients.values()) if (c.ready && c.subs.has(k)) c.send({ t: 'tiles', list: [[x, y, m, owner]] });
}

function gain(c, what, n) { c.inv[what] = (c.inv[what] || 0) + n; }
function stateSave(c) {
  qState.run(c.key, c.map, Math.round(c.x), Math.round(c.y), Math.round(c.hp), c.kills, JSON.stringify(c.inv));
}
function sendVitals(c, extra) {
  const o = { t: 'vitals', hp: Math.round(c.hp), maxHp: c.maxHp, inv: c.inv, kills: c.kills, atk: c.atk };
  if (extra) Object.assign(o, extra);
  c.send(o);
}

// ---------- messages -------------------------------------------------------
function onMessage(c, msg) {
  switch (msg.t) {
    case 'hello': {
      const key = String(msg.key || '').slice(0, 64);
      // Never drop this silently: a client that fails here looks identical to a dead
      // socket ("connected" but permanently blank), which is a miserable thing to debug.
      if (!key) return c.send({ t: 'err', err: 'handshake rejected: no key' });
      const name = String(msg.name || '').trim().slice(0, 18) || 'WANDERER';
      const prev = qPlayGet.get(key);
      const hue = prev ? prev.hue : (T.hash2(key.length, key.charCodeAt(0) | 0, 7) % 360);
      const now = Date.now();
      qPlay.run(key, name, hue, prev ? now : now, now);

      c.key = key; c.name = name; c.hue = hue; c.ready = true;

      const st = qStateGet.get(key);
      if (st) {
        c.map = st.map; c.x = st.x; c.y = st.y;
        c.hp = Math.max(1, st.hp); c.kills = st.kills;
        try { c.inv = Object.assign({ wood: 0, ore: 0, herb: 0, crystal: 0 }, JSON.parse(st.inv)); } catch (e) {}
      } else {
        const sp = T.spawnPoint(0);
        c.map = 0; c.x = sp.x; c.y = sp.y;
      }
      c.atk = BASE_ATK + Math.floor(c.kills / 3);
      c.energy = ENERGY_MAX;

      c.send({
        t: 'welcome', id: c.id, key, name, hue, map: c.map, x: c.x, y: c.y,
        hp: Math.round(c.hp), maxHp: c.maxHp, atk: c.atk, inv: c.inv, kills: c.kills,
        world: { w: W, h: H, chunk: CHUNK },
        maps: T.MAPS.map(m => ({ id: m.id, name: m.name, tier: m.tier, desc: m.desc })),
        spawn: T.spawnPoint(c.map),
        energy: c.energy, energyMax: ENERGY_MAX, reach: REACH, attackRange: ATTACK_RANGE,
        claimed: countClaims(c.map), total: W * H, online: live(), mapGrid: MAPGRID
      });
      setView(c, c.x, c.y);
      world.activate(c.map, c.x, c.y);
      console.log(`[net] ${name} joined map ${c.map} at ${Math.round(c.x)},${Math.round(c.y)} (${live()} online)`);
      break;
    }

    case 'view':
      if (!c.ready) return;
      setView(c, msg.x | 0, msg.y | 0);
      world.activate(c.map, msg.x | 0, msg.y | 0);
      break;

    case 'move': {
      if (!c.ready || c.dead) return;
      const now = Date.now();
      const dt = Math.min(1, (now - c.lastMove) / 1000);
      c.lastMove = now;
      const nx = Math.max(0, Math.min(W - 1, +msg.x || 0));
      const ny = Math.max(0, Math.min(H - 1, +msg.y || 0));
      const maxStep = dt * 14 + 2;                       // ~14 tiles/s + latency slack
      const dx = nx - c.x, dy = ny - c.y;
      if (dx * dx + dy * dy <= maxStep * maxStep) { c.x = nx; c.y = ny; }
      setView(c, c.x, c.y);
      break;
    }

    case 'travel': {
      if (!c.ready) return;
      const id = msg.map | 0;
      const def = T.MAPS.find(m => m.id === id);
      if (!def) return c.send({ t: 'deny2', r: 'no such map' });
      c.map = id;
      const sp = T.spawnPoint(id);
      c.x = sp.x; c.y = sp.y;
      c.sent.clear(); c.subs = new Set();
      c.send({
        t: 'arrived', map: id, name: def.name, desc: def.desc, spawn: sp, x: c.x, y: c.y,
        claimed: countClaims(id), total: W * H, maps: T.MAPS.map(m => ({ id: m.id, name: m.name, tier: m.tier, desc: m.desc }))
      });
      setView(c, c.x, c.y);
      world.activate(id, c.x, c.y);
      stateSave(c);
      console.log(`[net] ${c.name} travelled to #${id} ${def.name}`);
      break;
    }

    case 'set': {
      if (!c.ready || c.dead) return;
      const x = msg.x | 0, y = msg.y | 0, m = msg.m | 0;
      if (x < 0 || y < 0 || x >= W || y >= H) return c.send({ t: 'deny', x, y, r: 'bounds' });
      const dx = x - c.x, dy = y - c.y;
      if (dx * dx + dy * dy > REACH * REACH) return c.send({ t: 'deny', x, y, r: 'reach' });
      const key = c.map + ':' + (y * W + x);
      const cur = tiles.get(key);
      if (cur && cur.owner !== c.key) return c.send({ t: 'deny', x, y, r: 'owned' });
      const b0 = T.baseTypeFor(c.map, x, y);
      if (m === 0 && b0 === T.ID.VOID) return c.send({ t: 'deny', x, y, r: 'bounds' });

      const isRelease = (m === 0);
      if (!isRelease && !T.isPlaceable(m)) return c.send({ t: 'deny', x, y, r: 'material' });
      if (c.energy < (isRelease ? RELEASE_COST : COST)) return c.send({ t: 'deny', x, y, r: 'energy' });

      const cx = T.chunkOf(x), cy = T.chunkOf(y);
      if (isRelease) {
        if (!cur) return;
        tiles.delete(key);
        qDel.run(c.map, x, y);
        const d = densFor(c.map), i = (((y / MAPSTEP) | 0) * MAPGRID) + ((x / MAPSTEP) | 0);
        if (d[i] > 0) d[i]--;
        broadcastTile(c.map, cx, cy, x, y, -1, '');
        c.send({ t: 'unclaim', x, y, claimed: countClaims(c.map) });
      } else {
        tiles.set(key, { m, owner: c.key, map: c.map, x, y });
        qTile.run(c.map, x, y, m, c.key, Date.now());
        if (!cur) {
          const d = densFor(c.map), i = (((y / MAPSTEP) | 0) * MAPGRID) + ((x / MAPSTEP) | 0);
          if (d[i] < 255) d[i]++;
        }
        broadcastTile(c.map, cx, cy, x, y, m, c.key);
        c.energy -= COST;
        c.send({ t: 'you', x, y, m, claimed: countClaims(c.map), energy: c.energy });
      }
      break;
    }

    case 'harvest': {
      if (!c.ready || c.dead) return;
      const x = msg.x | 0, y = msg.y | 0;
      const dx = x - c.x, dy = y - c.y;
      if (dx * dx + dy * dy > REACH * REACH) return c.send({ t: 'harvested', x, y, err: 'out of reach' });
      const r = world.harvest(c, x, y);
      if (r.err) return c.send({ t: 'harvested', x, y, err: r.err, wait: r.wait });
      if (r.yielded) {
        gain(c, r.yields, r.amount);
        stateSave(c);
        const ripeSec = Math.ceil((r.ripe - Date.now()) / 1000);
        broadcastNode(c.map, x, y, r.kind, 0, ripeSec);
        c.send({ t: 'harvested', x, y, kind: r.kind, state: 0, ripeSec, gains: { [r.yields]: r.amount }, inv: c.inv });
      } else {
        c.send({ t: 'harvested', x, y, kind: r.kind, state: 1, partial: true, inv: c.inv });
      }
      break;
    }

    case 'attack': {
      if (!c.ready || c.dead) return;
      const r = world.attack(c, msg.id | 0);
      if (r.err) return c.send({ t: 'combat', err: r.err, id: msg.id | 0 });
      if (r.killed) {
        c.kills += 1;
        c.atk = BASE_ATK + Math.floor(c.kills / 3);
        gain(c, r.loot, 1);
        stateSave(c);
        c.send({ t: 'combat', id: r.id, killed: true, name: r.name, loot: r.loot, kills: c.kills, atk: c.atk, inv: c.inv });
      } else {
        c.send({ t: 'combat', id: r.id, killed: false, name: r.name, hp: r.hp, maxHp: r.maxHp });
      }
      break;
    }

    case 'map': {
      if (!c.ready) return;
      const map = (msg.map === undefined) ? c.map : (msg.map | 0);
      const d = densFor(map);
      c.send({ t: 'map', map, grid: MAPGRID, step: MAPSTEP, d: Buffer.from(d).toString(B64), claimed: countClaims(map) });
      break;
    }

    case 'ping':
      c.send({ t: 'pong', c: msg.c });
      break;
  }
}

function countClaims(map) {
  let n = 0;
  for (const t of tiles.values()) if (t.map === map) n++;
  return n;
}
function broadcastNode(map, x, y, kind, state, ripeSec) {
  const cx = T.chunkOf(x), cy = T.chunkOf(y), k = subKey(map, cx, cy);
  for (const c of clients.values()) if (c.ready && c.subs.has(k)) c.send({ t: 'node', map, x, y, kind, state, ripeSec });
}

// ---------- ticks ----------------------------------------------------------
setInterval(() => {
  for (const c of clients.values()) {
    if (c.ready) c.energy = Math.min(ENERGY_MAX, c.energy + 1);
  }
}, REGEN_MS);

// world simulation: monsters move, fight, respawn; depleted nodes come back
setInterval(() => {
  const ps = ready().filter(c => !c.dead);
  if (!ps.length) return;
  const now = Date.now();
  const ev = world.tick(ps, now);

  for (const r of ev.revived) broadcastNode(r.map, r.x, r.y, r.kind, 1, 0);
  for (const m of ev.respawned) {
    for (const c of clients.values()) if (c.ready && c.map === m.map) c.send({ t: 'mon', id: m.id, kind: m.kind, x: m.x, y: m.y, hp: 1, maxHp: 1, spawn: true });
  }

  for (const h of ev.hits) {
    for (const c of clients.values()) {
      if (!c.ready || c.key !== h.key) continue;
      c.hp -= h.dmg;
      if (c.hp <= 0) {
        c.hp = c.maxHp; c.dead = false;
        const sp = T.spawnPoint(c.map);
        c.x = sp.x; c.y = sp.y;
        c.sent.clear(); c.subs = new Set();
        stateSave(c);
        c.send({ t: 'died', by: h.name, spawn: sp, hp: c.hp, maxHp: c.maxHp });
        setView(c, c.x, c.y);
        console.log(`[net] ${c.name} was killed by ${h.name}`);
      } else {
        c.send({ t: 'dmg', dmg: h.dmg, by: h.name, hp: Math.round(c.hp), maxHp: c.maxHp });
      }
    }
  }
}, 100);

// presence + nearby monsters at 10Hz
setInterval(() => {
  const all = ready();
  if (!all.length) return;
  for (const c of all) {
    const near = [];
    for (const o of all) {
      if (o === c || o.map !== c.map) continue;
      if (Math.abs(o.x - c.x) > 72 || Math.abs(o.y - c.y) > 72) continue;
      near.push([o.key, o.name, Math.round(o.x * 10) / 10, Math.round(o.y * 10) / 10, o.hue]);
      if (near.length >= 64) break;
    }
    c.send({ t: 'players', list: near, you: [Math.round(c.x * 10) / 10, Math.round(c.y * 10) / 10, c.energy] });
    c.send({ t: 'mons', map: c.map, list: world.nearby(c.map, c.x, c.y) });
  }
}, 100);

setInterval(() => {
  const n = live();
  if (!n) return;
  for (const c of clients.values()) {
    if (!c.ready) continue;
    c.send({ t: 'stats', claimed: countClaims(c.map), total: W * H, online: n, volatile: world.stats() });
  }
}, 5000);

setInterval(() => {
  const now = Date.now();
  for (const c of clients.values()) if (c.ready && c.key) { qPlayLast.run(now, c.key); stateSave(c); }
}, 20000);

process.on('SIGINT', () => {
  console.log('\n[world] sealing world…');
  for (const c of clients.values()) if (c.ready && c.key) stateSave(c);
  try { db.exec('PRAGMA wal_checkpoint(TRUNCATE)'); } catch (e) {}
  process.exit(0);
});

server.listen(PORT, () => {
  console.log(`[world] STRATUM listening on http://127.0.0.1:${PORT}`);
  console.log(`[world] ${T.MAPS.length} maps, each ${W}x${H} = ${(W * H).toLocaleString()} tiles`);
  for (const m of T.MAPS) {
    const sp = T.spawnPoint(m.id);
    console.log(`[world]   #${m.id} ${m.name} (seed ${m.seed}) spawn ${sp.x},${sp.y} — ${m.desc}`);
  }
  console.log(`[volatile] ${JSON.stringify(world.stats())}`);
});
