'use strict';
/**
 * STRATUM — persistent shared-world server.
 *
 * TWO LAYERS, TWO RULES:
 *   PERSISTENT — the land. Player-placed tiles are owned absolutely and never reset.
 *                Nobody can overwrite anyone's tiles. No admins, no moderation queue.
 *   VOLATILE   — the provisions. Resource nodes and monsters respawn on timers. They are
 *                generated by the world, not authored by players, so resetting them costs
 *                nobody anything. See world.js.
 *
 * Zero dependencies: node:http + node:sqlite + a hand-rolled RFC 6455 WebSocket layer.
 */
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');
const T = require('./public/terrain.js');
const { World, ATTACK_RANGE } = require('./world.js');
const ECO = require('./src/economy.js');

const PORT = Number(process.env.PORT || 8090);
const PUB = path.join(__dirname, 'public');
const DATA = path.join(__dirname, 'data');
fs.mkdirSync(DATA, { recursive: true });
const DBFILE = process.env.STRATUM_DB || path.join(DATA, 'world.db');

const W = T.W, H = T.H, CHUNK = T.CHUNK;
const REACH = 6;
const COST = 1, RELEASE_COST = 0, ENERGY_MAX = 240, REGEN_MS = 80;
const VIEW_RADIUS = 2;
const MAPGRID = 256, MAPSTEP = W / MAPGRID;
const B64 = 'base64';
const PLAYER_HP = 100, BASE_ATK = 7;

// ---------- hardening limits -----------------------------------------------
// Everything below arrives from an untrusted client. These ceilings are what stop one
// rude (or one buggy) peer from taking the whole world down with it. All of them are
// tunable through env vars so a test can tighten them without touching the protocol.
const envNum = (k, d) => { const n = Number(process.env[k]); return Number.isFinite(n) && n > 0 ? n : d; };
const MAX_FRAME = envNum('STRATUM_MAX_FRAME', 64 * 1024);        // hard cap on ONE inbound frame
const MAX_BUFFER = envNum('STRATUM_MAX_BUFFER', 256 * 1024);     // un-parsed bytes held per connection
const MAX_OUTBUF = envNum('STRATUM_MAX_OUTBUF', 4 * 1024 * 1024); // unsent bytes before we hang up
const MSG_PER_SEC = envNum('STRATUM_MSG_PER_SEC', 120);          // sustained inbound frames/second
const MSG_BURST = envNum('STRATUM_MSG_BURST', 240);              // tokens available at once
const FLOOD_SLACK = envNum('STRATUM_FLOOD_SLACK', MSG_BURST);    // dropped frames tolerated before cutoff
const MAX_CONN_PER_IP = envNum('STRATUM_MAX_CONN_PER_IP', 256);  // simultaneous sockets from one address
const MAX_CONNS = envNum('STRATUM_MAX_CONNS', 512);              // simultaneous sockets, period
const HS_IDLE_MS = envNum('STRATUM_HS_IDLE_MS', 15000);          // silence allowed before hello
const IDLE_MS = envNum('STRATUM_IDLE_MS', 90000);                // silence allowed after hello
const WS_PING_MS = envNum('STRATUM_WS_PING_MS', 20000);          // keepalive ping cadence
const KEY_RE = /^[\x21-\x7e]{1,64}$/;                            // printable ASCII player keys only

// ---------- persistence ----------------------------------------------------
const db = new DatabaseSync(DBFILE);
db.exec(`
  PRAGMA journal_mode = WAL;
  PRAGMA synchronous = NORMAL;
  CREATE TABLE IF NOT EXISTS players(
    k TEXT PRIMARY KEY, name TEXT NOT NULL, hue INTEGER NOT NULL,
    created INTEGER NOT NULL, last INTEGER NOT NULL);
  CREATE TABLE IF NOT EXISTS player_state(
    k TEXT PRIMARY KEY, map INTEGER NOT NULL, x REAL NOT NULL, y REAL NOT NULL,
    hp INTEGER NOT NULL, kills INTEGER NOT NULL, inv TEXT NOT NULL);
`);

// migrate a pre-maps tiles table (tiles used to be keyed by x,y only)
(function migrateTiles() {
  const cols = db.prepare('PRAGMA table_info(tiles)').all();
  const hasMap = cols.some(c => c.name === 'map');
  if (cols.length && !hasMap) {
    db.exec('ALTER TABLE tiles RENAME TO tiles_old');
    console.log('[db] migrating tiles table to per-map schema…');
  }
  db.exec(`CREATE TABLE IF NOT EXISTS tiles(
    map INTEGER NOT NULL, x INTEGER NOT NULL, y INTEGER NOT NULL, m INTEGER NOT NULL,
    owner TEXT NOT NULL, ts INTEGER NOT NULL, PRIMARY KEY(map,x,y));
    CREATE INDEX IF NOT EXISTS tiles_owner ON tiles(owner);`);
  if (cols.length && !hasMap) {
    db.exec('INSERT OR IGNORE INTO tiles(map,x,y,m,owner,ts) SELECT 0,x,y,m,owner,ts FROM tiles_old; DROP TABLE tiles_old;');
  }
})();

// tool tier rides beside the survival state; databases from before the economy
// gain the column on boot instead of failing the prepare below.
(function migrateTool() {
  try {
    const cols = db.prepare('PRAGMA table_info(player_state)').all();
    if (!cols.some(c => c.name === 'tool')) db.exec('ALTER TABLE player_state ADD COLUMN tool INTEGER NOT NULL DEFAULT 0');
  } catch (e) { console.log('[db] tool migration skipped:', e && e.message); }
})();

/** authoritative in-memory land: "map:y*W+x" -> {m, owner} */
const tiles = new Map();
const density = new Map();               // mapId -> Uint8Array(MAPGRID^2)
function densFor(map) {
  let d = density.get(map);
  if (!d) { d = new Uint8Array(MAPGRID * MAPGRID); density.set(map, d); }
  return d;
}
(function loadTiles() {
  const rows = db.prepare('SELECT map, x, y, m, owner FROM tiles').all();
  const perMap = {};
  for (const r of rows) {
    const key = r.map + ':' + (r.y * W + r.x);
    tiles.set(key, { m: r.m, owner: r.owner, map: r.map, x: r.x, y: r.y });
    const d = densFor(r.map);
    const i = (((r.y / MAPSTEP) | 0) * MAPGRID) + ((r.x / MAPSTEP) | 0);
    if (d[i] < 255) d[i]++;
    perMap[r.map] = (perMap[r.map] || 0) + 1;
  }
  const total = W * H;
  console.log(`[world] ${rows.length} owned tiles restored across ${Object.keys(perMap).length} map(s)`);
  for (const m of T.MAPS) {
    const c = perMap[m.id] || 0;
    console.log(`[world]   #${m.id} ${m.name}: ${c} claimed (${((c / total) * 100).toFixed(4)}%)`);
  }
})();

const qTile = db.prepare('INSERT OR REPLACE INTO tiles(map,x,y,m,owner,ts) VALUES(?,?,?,?,?,?)');
const qDel = db.prepare('DELETE FROM tiles WHERE map=? AND x=? AND y=?');
const qPlay = db.prepare('INSERT OR REPLACE INTO players(k,name,hue,created,last) VALUES(?,?,?,?,?)');
const qPlayGet = db.prepare('SELECT name,hue FROM players WHERE k=?');
const qPlayCount = db.prepare('SELECT COUNT(*) n FROM players');
const qPlayLast = db.prepare('UPDATE players SET last=? WHERE k=?');
const qState = db.prepare('INSERT OR REPLACE INTO player_state(k,map,x,y,hp,kills,inv,tool) VALUES(?,?,?,?,?,?,?,?)');
const qStateGet = db.prepare('SELECT * FROM player_state WHERE k=?');

const world = new World(db);

// ---------- static files ---------------------------------------------------
const MIME = {
  '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8', '.json': 'application/json',
  '.png': 'image/png', '.ico': 'image/x-icon', '.svg': 'image/svg+xml'
};

const server = http.createServer((req, res) => {
  const url = new URL(req.url, 'http://x');
  let p = decodeURIComponent(url.pathname);

  if (p === '/api/stats') {
    const bodies = {};
    for (const m of T.MAPS) {
      let c = 0;
      for (const t of tiles.values()) if (t.map === m.id) c++;
      bodies[m.id] = { name: m.name, claimed: c, pct: +((c / (W * H)) * 100).toFixed(5) };
    }
    const body = JSON.stringify({
      world: { w: W, h: H, tiles: W * H },
      maps: bodies,
      claimed: tiles.size,
      online: [...clients.values()].filter(c => c.ready).length,
      playersEver: qPlayCount.get().n,
      volatile: world.stats(),
      spawn: T.spawnPoint(0)
    }, null, 2);
    res.writeHead(200, { 'content-type': 'application/json', 'cache-control': 'no-store' });
    return res.end(body);
  }

  if (p === '/') p = '/index.html';
  const file = path.join(PUB, path.normalize(p));
  if (!file.startsWith(PUB)) { res.writeHead(403); return res.end('no'); }
  fs.readFile(file, (err, buf) => {
    if (err) { res.writeHead(404, { 'content-type': 'text/plain' }); return res.end('404'); }
    const ext = path.extname(file).toLowerCase();
    res.writeHead(200, {
      'content-type': MIME[ext] || 'application/octet-stream',
      'cache-control': (ext === '.html' || ext === '.js') ? 'no-store' : 'public, max-age=3600'
    });
    res.end(buf);
  });
});

// slowloris on the HTTP side: bound how long a request may dribble in, and how long a
// socket may sit silent before we stop paying for it.
server.headersTimeout = Math.min(20000, HS_IDLE_MS * 2);
server.requestTimeout = 60000;
server.keepAliveTimeout = 10000;
server.maxHeadersCount = 64;
server.on('connection', (socket) => {
  try { socket.setTimeout(HS_IDLE_MS, () => { try { socket.destroy(); } catch (e) {} }); } catch (e) {}
});
server.on('clientError', (err, socket) => {
  try { if (socket.writable && !socket.destroyed) socket.end('HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n'); } catch (e) {}
  try { socket.destroy(); } catch (e) {}
});
server.on('error', (e) => {
  console.log('[fatal] http server error (still serving):', e && (e.stack || e.message));
});

// ---------- websocket ------------------------------------------------------
const GUID = '258EAFA5-E914-47DA-95CA-C5AB0DC85B11';
const clients = new Map();
const connsByIp = new Map();               // address -> Set<socket>: the per-IP connection cap
let nextId = 1;

const OP_TEXT = 0x1, OP_CLOSE = 0x8, OP_PING = 0x9, OP_PONG = 0xA;

/** Token bucket. False means "this frame arrived too fast to be served". */
function admit(c, now) {
  const dt = (now - c.tokenAt) / 1000;
  if (dt > 0) { c.tokens = Math.min(MSG_BURST, c.tokens + dt * MSG_PER_SEC); c.tokenAt = now; }
  if (c.tokens >= 1) { c.tokens -= 1; return true; }
  c.dropped++;
  return false;
}

/** Where a connection really comes from. Behind a tunnel every peer looks local, so a
 *  forwarded-for header is honoured when present and plausible. */
function ipOf(req) {
  const xff = req.headers['x-forwarded-for'];
  if (typeof xff === 'string' && xff) {
    const first = xff.split(',')[0].trim();
    if (first.length && first.length <= 45 && /^[0-9a-fA-F:.\[\]]+$/.test(first)) return first;
  }
  const ip = (req.socket && req.socket.remoteAddress) || 'unknown';
  return ip.startsWith('::ffff:') ? ip.slice(7) : ip;
}

function closeFrame(code, reason) {
  const r = Buffer.from(String(reason || '').slice(0, 60), 'utf8');
  const p = Buffer.alloc(2 + r.length);
  p.writeUInt16BE(code, 0);
  r.copy(p, 2);
  return wsEncode(p, OP_CLOSE);
}

/** Tear one connection down for good: close frame, FIN, then a hard destroy if the peer
 *  will not let go. Never throws — teardown has to work on a half-dead socket too. */
function dropClient(c, why) {
  if (!c || c.gone) return;
  c.gone = true;
  try { console.log(`[net] #${c.id}${c.name ? ' ' + c.name : ''} dropped: ${why} (${live()} online)`); } catch (e) {}
  const s = c.sock;
  try { s.write(closeFrame(why === 'frame too large' ? 1009 : 1008, why)); } catch (e) {}
  try { s.end(); } catch (e) {}
  const t = setTimeout(() => { try { s.destroy(); } catch (e) {} }, 250);
  if (t && t.unref) t.unref();
  clients.delete(s);
}

function wsEncode(str, opcode) {
  const payload = Buffer.from(str, 'utf8');
  const len = payload.length;
  let head;
  if (len < 126) { head = Buffer.alloc(2); head[1] = len; }
  else if (len < 65536) { head = Buffer.alloc(4); head[1] = 126; head.writeUInt16BE(len, 2); }
  else { head = Buffer.alloc(10); head[1] = 127; head.writeBigUInt64BE(BigInt(len), 2); }
  head[0] = 0x80 | (opcode === undefined ? 1 : opcode);
  return Buffer.concat([head, payload]);
}

server.on('upgrade', (req, socket) => {
  const key = req.headers['sec-websocket-key'];
  if (!key || socket.destroyed) { try { socket.destroy(); } catch (e) {} return; }

  // Connection caps come first: a peer that is already over its allowance costs us
  // nothing but a 503, and a socket we never accepted can never become a client.
  const ip = ipOf(req);
  let byIp = connsByIp.get(ip);
  if (!byIp) { byIp = new Set(); connsByIp.set(ip, byIp); }
  if (byIp.size >= MAX_CONN_PER_IP || clients.size >= MAX_CONNS) {
    console.log(`[net] refused ${ip}: ${byIp.size} open from that address (cap ${MAX_CONN_PER_IP}), ${clients.size} total`);
    // end() (not destroy()) so the refusal is actually flushed to the peer
    try { socket.end('HTTP/1.1 503 Service Unavailable\r\nConnection: close\r\nContent-Length: 0\r\n\r\n'); } catch (e) {}
    const t = setTimeout(() => { try { socket.destroy(); } catch (e) {} }, 250);
    if (t && t.unref) t.unref();
    if (!byIp.size) connsByIp.delete(ip);
    return;
  }
  byIp.add(socket);

  socket.write(
    'HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\n' +
    'Sec-WebSocket-Accept: ' + crypto.createHash('sha1').update(key + GUID).digest(B64) + '\r\n\r\n'
  );
  socket.setNoDelay(true);
  socket.setTimeout(HS_IDLE_MS);      // silence before hello costs the socket

  const c = {
    id: nextId++, sock: socket, ip, key: null, name: null, hue: 0, map: 0,
    x: 0, y: 0, hp: PLAYER_HP, maxHp: PLAYER_HP, kills: 0, atk: BASE_ATK,
    inv: { wood: 0, ore: 0, herb: 0, crystal: 0 }, tool: 0, atkBoost: 0,
    energy: ENERGY_MAX, subs: new Set(), sent: new Set(),
    ready: false, lastMove: Date.now(), dead: false,
    gone: false, bad: 0, lastRx: Date.now(), tokenAt: Date.now(), tokens: MSG_BURST, dropped: 0,
    send(obj) {
      if (c.gone || socket.destroyed) return;
      // a peer that stops reading must not be able to grow our memory: drop it instead
      if (socket.writableLength > MAX_OUTBUF) return dropClient(c, 'outbound backlog');
      try { socket.write(wsEncode(JSON.stringify(obj))); } catch (e) {}
    }
  };
  clients.set(socket, c);

  let buf = Buffer.alloc(0);
  socket.on('data', (chunk) => {
    c.lastRx = Date.now();
    try {
      if (c.gone) return;
      if (buf.length + chunk.length > MAX_BUFFER) return dropClient(c, 'buffered bytes');
      buf = buf.length ? Buffer.concat([buf, chunk]) : chunk;
      for (;;) {
        if (c.gone) return;
        if (buf.length < 2) return;
        const b0 = buf[0], b1 = buf[1];
        const op = b0 & 0x0f;
        const masked = (b1 & 0x80) !== 0;
        let len = b1 & 0x7f, off = 2;
        if (len === 126) { if (buf.length < 4) return; len = buf.readUInt16BE(2); off = 4; }
        else if (len === 127) { if (buf.length < 10) return; len = Number(buf.readBigUInt64BE(2)); off = 10; }
        // A frame's size is declared in its header, so it is policed there: a client that
        // announces a huge frame is refused before we buffer a single byte of it.
        if (!Number.isFinite(len) || len < 0 || len > MAX_FRAME) return dropClient(c, 'frame too large');
        let mask = null;
        if (masked) { if (buf.length < off + 4) return; mask = buf.subarray(off, off + 4); off += 4; }
        if (buf.length < off + len) return;
        let payload = Buffer.from(buf.subarray(off, off + len));
        buf = buf.subarray(off + len);
        if (mask) for (let i = 0; i < payload.length; i++) payload[i] ^= mask[i & 3];

        // every frame, including control frames, is billed against the rate limit
        if (!admit(c, Date.now())) {
          if (c.dropped > FLOOD_SLACK) return dropClient(c, 'rate limit exceeded');
          continue;                                  // short burst: frame dropped, socket kept
        }

        if (op === OP_CLOSE) return dropClient(c, 'client close');
        if (op === OP_PING) { try { socket.write(wsEncode(payload.toString('utf8'), OP_PONG)); } catch (e) {} continue; }
        if (op === OP_PONG) continue;
        if (op !== OP_TEXT) continue;                // binary / unknown opcode: consumed, ignored

        let msg;
        try { msg = JSON.parse(payload.toString('utf8')); }
        catch (e) { c.bad++; continue; }             // malformed JSON: ignored, connection kept
        try { onMessage(c, msg); }
        catch (e) { console.log('[err]', e && (e.stack || e.message)); }
      }
    } catch (e) {
      // a decoder fault must never take the process with it
      console.log('[err] frame decode:', e && (e.stack || e.message));
      dropClient(c, 'decode error');
    }
  });
  socket.on('error', () => {});
  // An upgraded socket is half-open by default, so a peer that closes (or dies) shows up
  // as 'end' — never as 'close'. Without this, dead connections would keep their slot in
  // the per-IP ledger and their entry in the client map until an idle sweep caught them.
  socket.on('end', () => dropClient(c, 'peer closed'));
  socket.on('close', () => {
    clients.delete(socket);
    const s = connsByIp.get(ip);
    if (s) { s.delete(socket); if (!s.size) connsByIp.delete(ip); }
    console.log(`[net] ${c.name || '#' + c.id} left (${live()} online)`);
  });
  console.log(`[net] #${c.id} connected`);
});

function live() { return [...clients.values()].filter(c => c.ready).length; }
function ready() { return [...clients.values()].filter(c => c.ready); }
function subKey(map, cx, cy) { return map + ':' + cx + ':' + cy; }

function sendChunk(c, cx, cy) {
  const map = c.map;
  const x0 = cx * CHUNK, y0 = cy * CHUNK;
  const out = []; const owners = []; const oIdx = new Map();
  for (let j = 0; j < CHUNK; j++) {
    for (let i = 0; i < CHUNK; i++) {
      const t = tiles.get(map + ':' + ((y0 + j) * W + (x0 + i)));
      if (!t) continue;
      let oi = oIdx.get(t.owner);
      if (oi === undefined) { oi = owners.length; owners.push(t.owner); oIdx.set(t.owner, oi); }
      out.push(i, j, t.m, oi);
    }
  }
  const bytes = new Uint8Array(out.length);
  for (let i = 0; i < out.length; i++) bytes[i] = out[i] & 0xff;
  c.send({
    t: 'chunk', map, cx, cy, n: out.length / 4,
    d: Buffer.from(bytes).toString(B64), owners,
    nodes: world.nodesForChunk(map, cx, cy)
  });
}

function setView(c, tx, ty) {
  const ccx = T.chunkOf(tx), ccy = T.chunkOf(ty);
  const want = new Set();
  for (let dy = -VIEW_RADIUS; dy <= VIEW_RADIUS; dy++) {
    for (let dx = -VIEW_RADIUS; dx <= VIEW_RADIUS; dx++) {
      const cx = ccx + dx, cy = ccy + dy;
      if (cx < 0 || cy < 0 || cx * CHUNK >= W || cy * CHUNK >= H) continue;
      want.add(subKey(c.map, cx, cy));
    }
  }
  const fresh = [];
  for (const k of want) {
    if (!c.sent.has(k)) { c.sent.add(k); const p = k.split(':'); fresh.push([+p[1], +p[2]]); }
  }
  // forget subscriptions to other maps
  for (const k of [...c.sent]) if (!k.startsWith(c.map + ':')) c.sent.delete(k);
  c.subs = want;
  for (const f of fresh) sendChunk(c, f[0], f[1]);
}

function broadcastTile(map, cx, cy, x, y, m, owner) {
  const k = subKey(map, cx, cy);
  for (const c of clients.values()) if (c.ready && c.subs.has(k)) c.send({ t: 'tiles', list: [[x, y, m, owner]] });
}

function gain(c, what, n) { c.inv[what] = (c.inv[what] || 0) + n; }
/** Best owned bonus of a gear kind: weapons add damage, armour soaks it. Zero when bare. */
function gearBonus(inv, kind) {
  let best = 0;
  if (!inv || typeof inv !== 'object') return 0;
  for (const k of Object.keys(inv)) {
    if (!inv[k]) continue;
    const it = ECO.itemOf(k);
    if (!it || it.kind !== kind) continue;
    if (kind === 'weapon') best = Math.max(best, it.damageBonus | 0);
    else best = Math.max(best, it.mitigation | 0);
  }
  return best;
}
function stateSave(c) {
  qState.run(c.key, c.map, Math.round(c.x), Math.round(c.y), Math.round(c.hp), c.kills, JSON.stringify(c.inv), c.tool | 0);
}
function sendVitals(c, extra) {
  const o = { t: 'vitals', hp: Math.round(c.hp), maxHp: c.maxHp, inv: c.inv, kills: c.kills, atk: c.atk, tool: c.tool | 0, level: world.hunter(c).level };
  if (extra) Object.assign(o, extra);
  c.send(o);
}

// ---------- inbound validation ---------------------------------------------
// One rule for every field a client controls: a value that is not a finite number is
// refused outright (NaN, Infinity, null and "12" are not coordinates), and a finite one
// is clamped into the world before it is allowed anywhere near game state.
const isFin = (v) => typeof v === 'number' && Number.isFinite(v);
function clampInt(v, lo, hi, dflt) {
  if (!isFin(v)) return dflt;
  return Math.max(lo, Math.min(hi, Math.trunc(v)));
}
/** Finite coordinate clamped into [0, n-1], or null when it was not a number at all. */
function clampCoord(v, n) {
  if (!isFin(v)) return null;
  return Math.max(0, Math.min(n - 1, Math.trunc(v)));
}
/** Finite coordinate that must already lie inside [0, n-1]; null otherwise. */
function inBounds(v, n) {
  if (!isFin(v)) return null;
  const i = Math.trunc(v);
  return (i < 0 || i >= n) ? null : i;
}
/** Untrusted text -> bounded, printable, control-character-free string. */
function cleanText(v, max) {
  if (isFin(v)) v = String(v);
  if (typeof v !== 'string') return '';
  return v.replace(/[\x00-\x1f\x7f]/g, '').trim().slice(0, max);
}

// ---------- messages -------------------------------------------------------
// The complete set of things a client may say. Anything else is ignored on sight: the
// server never dispatches a type it does not know, so a new type cannot reach any code
// path by accident.
const INBOUND = new Set(['hello', 'move', 'view', 'set', 'release', 'harvest', 'attack', 'travel', 'map', 'ping', 'craft', 'toolup']);

function onMessage(c, msg) {
  if (!msg || typeof msg !== 'object' || Array.isArray(msg)) { c.bad++; return; }
  if (typeof msg.t !== 'string' || !INBOUND.has(msg.t)) { c.bad++; return; }
  switch (msg.t) {
    case 'hello': {
      const key = (typeof msg.key === 'string') ? msg.key.slice(0, 64)
        : (isFin(msg.key) ? String(msg.key).slice(0, 64) : '');
      // Never drop this silently: a client that fails here looks identical to a dead
      // socket ("connected" but permanently blank), which is a miserable thing to debug.
      if (!key) return c.send({ t: 'err', err: 'handshake rejected: no key' });
      if (!KEY_RE.test(key)) return c.send({ t: 'err', err: 'handshake rejected: bad key' });
      const name = cleanText(msg.name, 18) || 'WANDERER';
      const prev = qPlayGet.get(key);
      const hue = prev ? prev.hue : (T.hash2(key.length, key.charCodeAt(0) | 0, 7) % 360);
      const now = Date.now();
      qPlay.run(key, name, hue, prev ? now : now, now);

      c.key = key; c.name = name; c.hue = hue; c.ready = true;
      try { c.sock.setTimeout(0); } catch (e) {}   // idle handling now runs on pings + the sweep

      const st = qStateGet.get(key);
      if (st) {
        c.map = st.map; c.x = st.x; c.y = st.y;
        c.hp = Math.max(1, st.hp); c.kills = st.kills;
        try { c.inv = Object.assign({ wood: 0, ore: 0, herb: 0, crystal: 0 }, JSON.parse(st.inv)); } catch (e) {}
        c.tool = (st && Number.isFinite(+st.tool)) ? Math.max(0, Math.min(ECO.maxToolTier(), (+st.tool) | 0)) : 0;
      } else {
        const sp = T.spawnPoint(0);
        c.map = 0; c.x = sp.x; c.y = sp.y;
        // new arrivals wash up with salvaged materials: enough for a first shelter,
        // never enough to skip the harvest loop.
        c.inv = { wood: 6, ore: 4, herb: 2, crystal: 1 };
        c.tool = 0;
      }
      c.atk = BASE_ATK + Math.floor(c.kills / 3);
      c.atkBoost = gearBonus(c.inv, 'weapon');
      c.energy = ENERGY_MAX;

      c.send({
        t: 'welcome', id: c.id, key, name, hue, map: c.map, x: c.x, y: c.y,
        hp: Math.round(c.hp), maxHp: c.maxHp, atk: c.atk, inv: c.inv, kills: c.kills,
        tool: c.tool | 0, level: world.hunter(c).level,
        catalog: {
          costs: ECO.MATERIAL_COSTS.map(co => Object.assign({}, co)),
          names: ECO.MATERIAL_NAMES.slice(),
          recipes: ECO.RECIPES.map(r => ({ id: r.id, tier: r.tier, inputs: Object.assign({}, r.inputs), output: { item: r.output.item, count: r.output.count } })),
          items: Object.assign({}, ECO.ITEMS),
          tools: ECO.TOOL_TIERS.map(t => ({ tier: t.tier, id: t.id, name: t.name, cost: Object.assign({}, t.cost) }))
        },
        world: { w: W, h: H, chunk: CHUNK },
        maps: T.MAPS.map(m => ({ id: m.id, name: m.name, tier: m.tier, desc: m.desc })),
        spawn: T.spawnPoint(c.map),
        energy: c.energy, energyMax: ENERGY_MAX, reach: REACH, attackRange: ATTACK_RANGE,
        claimed: countClaims(c.map), total: W * H, online: live(), mapGrid: MAPGRID
      });
      setView(c, c.x, c.y);
      world.activate(c.map, c.x, c.y);
      console.log(`[net] ${name} joined map ${c.map} at ${Math.round(c.x)},${Math.round(c.y)} (${live()} online)`);
      break;
    }

    case 'view': {
      if (!c.ready) return;
      const vx = clampCoord(msg.x, W), vy = clampCoord(msg.y, H);
      if (vx === null || vy === null) return;          // not a number: refused
      setView(c, vx, vy);
      world.activate(c.map, vx, vy);
      break;
    }

    case 'move': {
      if (!c.ready || c.dead) return;
      const mx = clampCoord(msg.x, W), my = clampCoord(msg.y, H);
      // NaN / Infinity / missing / null: the player does not move at all. (It used to
      // fall through a `| 0` and quietly teleport them to the origin.)
      if (mx === null || my === null) return;
      const now = Date.now();
      const dt = Math.min(1, Math.max(0, now - c.lastMove) / 1000);
      c.lastMove = now;
      const maxStep = dt * 14 + 2;                       // ~14 tiles/s + latency slack
      const dx = mx - c.x, dy = my - c.y;
      if (dx * dx + dy * dy <= maxStep * maxStep) { c.x = mx; c.y = my; }
      setView(c, c.x, c.y);
      break;
    }

    case 'travel': {
      if (!c.ready) return;
      const id = clampInt(msg.map, 0, 1024, -1);
      const def = T.MAPS.find(m => m.id === id);
      if (!def) return c.send({ t: 'deny2', r: 'no such map' });
      c.map = id;
      const sp = T.spawnPoint(id);
      c.x = sp.x; c.y = sp.y;
      c.sent.clear(); c.subs = new Set();
      c.send({
        t: 'arrived', map: id, name: def.name, desc: def.desc, spawn: sp, x: c.x, y: c.y,
        claimed: countClaims(id), total: W * H, maps: T.MAPS.map(m => ({ id: m.id, name: m.name, tier: m.tier, desc: m.desc }))
      });
      setView(c, c.x, c.y);
      world.activate(id, c.x, c.y);
      stateSave(c);
      console.log(`[net] ${c.name} travelled to #${id} ${def.name}`);
      break;
    }

    // 'release' is the named form of set-with-material-0: same wire shape, same handler,
    // it just hands the tile back to the commons.
    case 'set':
    case 'release': {
      if (!c.ready || c.dead) return;
      const x = inBounds(msg.x, W), y = inBounds(msg.y, H);
      if (x === null || y === null) {
        return c.send({ t: 'deny', x: clampInt(msg.x, 0, W - 1, 0), y: clampInt(msg.y, 0, H - 1, 0), r: 'bounds' });
      }
      const m = (msg.t === 'release') ? 0 : clampInt(msg.m, 0, 4095, -1);
      if (m < 0) return c.send({ t: 'deny', x, y, r: 'material' });
      const dx = x - c.x, dy = y - c.y;
      if (dx * dx + dy * dy > REACH * REACH) return c.send({ t: 'deny', x, y, r: 'reach' });
      const key = c.map + ':' + (y * W + x);
      const cur = tiles.get(key);
      if (cur && cur.owner !== c.key) return c.send({ t: 'deny', x, y, r: 'owned' });
      const b0 = T.baseTypeFor(c.map, x, y);
      if (m === 0 && b0 === T.ID.VOID) return c.send({ t: 'deny', x, y, r: 'bounds' });

      const isRelease = (m === 0);
      if (!isRelease && !T.isPlaceable(m)) return c.send({ t: 'deny', x, y, r: 'material' });
      if (c.energy < (isRelease ? RELEASE_COST : COST)) return c.send({ t: 'deny', x, y, r: 'energy' });
      // placing a tile spends harvested resources on top of will. The check and the
      // deduction both happen inside this one synchronous handler, so nothing can
      // slip between them.
      if (!isRelease) {
        const cost = ECO.costOfTile(m);
        if (cost && !ECO.canAfford(c.inv, cost)) {
          return c.send({ t: 'deny', x, y, r: 'resources', need: cost, missing: ECO.missingFor(c.inv, cost) });
        }
      }

      const cx = T.chunkOf(x), cy = T.chunkOf(y);
      if (isRelease) {
        if (!cur) return;
        tiles.delete(key);
        qDel.run(c.map, x, y);
        const d = densFor(c.map), i = (((y / MAPSTEP) | 0) * MAPGRID) + ((x / MAPSTEP) | 0);
        if (d[i] > 0) d[i]--;
        broadcastTile(c.map, cx, cy, x, y, -1, '');
        c.send({ t: 'unclaim', x, y, claimed: countClaims(c.map) });
      } else {
        tiles.set(key, { m, owner: c.key, map: c.map, x, y });
        qTile.run(c.map, x, y, m, c.key, Date.now());
        if (!cur) {
          const d = densFor(c.map), i = (((y / MAPSTEP) | 0) * MAPGRID) + ((x / MAPSTEP) | 0);
          if (d[i] < 255) d[i]++;
        }
        broadcastTile(c.map, cx, cy, x, y, m, c.key);
        c.energy -= COST;
        const pcost = ECO.costOfTile(m);
        if (pcost) { const paid = ECO.applyCost(c.inv, pcost); if (paid) c.inv = paid; }
        stateSave(c);
        c.send({ t: 'you', x, y, m, claimed: countClaims(c.map), energy: c.energy, inv: c.inv });
      }
      break;
    }

    case 'harvest': {
      if (!c.ready || c.dead) return;
      const x = inBounds(msg.x, W), y = inBounds(msg.y, H);
      if (x === null || y === null) return;      // not a coordinate: never answered as if it were
      const dx = x - c.x, dy = y - c.y;
      if (dx * dx + dy * dy > REACH * REACH) return c.send({ t: 'harvested', x, y, err: 'out of reach' });
      const r = world.harvest(c, x, y);
      if (r.err) return c.send({ t: 'harvested', x, y, err: r.err, wait: r.wait });
      if (r.yielded) {
        // better tools pay off more; a tool never pays off LESS than bare hands.
        const boosted = ECO.toolHarvestAmount(c.tool | 0, r.kind);
        const amount = (typeof boosted === 'number') ? Math.max(r.amount, boosted) : r.amount;
        gain(c, r.yields, amount);
        stateSave(c);
        const ripeSec = Math.ceil((r.ripe - Date.now()) / 1000);
        broadcastNode(c.map, x, y, r.kind, 0, ripeSec);
        c.send({ t: 'harvested', x, y, kind: r.kind, state: 0, ripeSec, gains: { [r.yields]: amount }, inv: c.inv });
      } else {
        c.send({ t: 'harvested', x, y, kind: r.kind, state: 1, partial: true, inv: c.inv });
      }
      break;
    }

    case 'attack': {
      if (!c.ready || c.dead) return;
      const mid = clampInt(msg.id, 0, 0x7fffffff, -1);
      if (mid < 0) return c.send({ t: 'combat', err: 'no such creature', id: 0 });
      c.atkBoost = gearBonus(c.inv, 'weapon');
      const r = world.attack(c, mid);
      if (r.err) return c.send({ t: 'combat', err: r.err, id: mid });
      if (r.killed) {
        c.kills += 1;
        c.atk = BASE_ATK + Math.floor(c.kills / 3);
        gain(c, r.loot, 1);
        stateSave(c);
        c.send({ t: 'combat', id: r.id, killed: true, name: r.name, loot: r.loot, kills: c.kills, atk: c.atk, inv: c.inv, level: world.hunter(c).level });
      } else {
        c.send({ t: 'combat', id: r.id, killed: false, name: r.name, hp: r.hp, maxHp: r.maxHp });
      }
      break;
    }

    case 'craft': {
      if (!c.ready || c.dead) return;
      const id = cleanText(msg.id, 32);
      const rec = ECO.recipeById(id);
      if (!rec) return c.send({ t: 'crafted', err: 'unknown recipe', id });
      if (rec.tier > (c.tool | 0)) return c.send({ t: 'crafted', err: 'locked: needs ' + (ECO.toolTier(rec.tier) || {}).name + ' tools', id });
      const res = ECO.craft(id, c.inv);
      if (!res.ok) return c.send({ t: 'crafted', err: res.error, id });
      c.inv = res.inv;
      c.atkBoost = gearBonus(c.inv, 'weapon');
      stateSave(c);
      sendVitals(c);
      c.send({ t: 'crafted', id, item: res.item, count: res.count, inv: c.inv, atkBoost: c.atkBoost });
      break;
    }

    case 'toolup': {
      if (!c.ready || c.dead) return;
      const next = (c.tool | 0) + 1;
      const cost = ECO.toolCost(next);
      const tier = ECO.toolTier(next);
      if (!cost || !tier) return c.send({ t: 'tooled', err: 'already at the best tools' });
      if (!ECO.canAfford(c.inv, cost)) {
        return c.send({ t: 'tooled', err: 'not enough resources', need: cost, missing: ECO.missingFor(c.inv, cost) });
      }
      const paid = ECO.applyCost(c.inv, cost);
      if (!paid) return c.send({ t: 'tooled', err: 'not enough resources', need: cost, missing: ECO.missingFor(c.inv, cost) });
      c.inv = paid;
      c.tool = next;
      stateSave(c);
      sendVitals(c);
      c.send({ t: 'tooled', tool: next, name: tier.name, inv: c.inv });
      break;
    }

    case 'map': {
      if (!c.ready) return;
      // Never densFor() an id the world does not have: that would allocate a fresh grid
      // per invented map number, which is a cheap way to eat all the memory we have.
      let map = (msg.map === undefined) ? c.map : clampInt(msg.map, 0, 1024, c.map);
      if (!T.MAPS.some(m => m.id === map)) map = c.map;
      const d = densFor(map);
      c.send({ t: 'map', map, grid: MAPGRID, step: MAPSTEP, d: Buffer.from(d).toString(B64), claimed: countClaims(map) });
      break;
    }

    case 'ping': {
      // echoed, but bounded: a client must not be able to make us repeat a payload back
      const echo = isFin(msg.c) ? Math.trunc(msg.c) : (cleanText(msg.c, 32) || null);
      c.send({ t: 'pong', c: echo });
      break;
    }
  }
}

function countClaims(map) {
  let n = 0;
  for (const t of tiles.values()) if (t.map === map) n++;
  return n;
}
function broadcastNode(map, x, y, kind, state, ripeSec) {
  const cx = T.chunkOf(x), cy = T.chunkOf(y), k = subKey(map, cx, cy);
  for (const c of clients.values()) if (c.ready && c.subs.has(k)) c.send({ t: 'node', map, x, y, kind, state, ripeSec });
}

// ---------- ticks ----------------------------------------------------------
// Every timer body is wrapped: a fault in one tick (or in one client's data) must cost
// us that tick, not the world. Repeated faults log at most once per 5s so a throwing
// condition can never be turned into a log flood.
function every(ms, label, fn) {
  let lastLog = 0;
  setInterval(() => {
    try { fn(); }
    catch (e) {
      const now = Date.now();
      if (now - lastLog > 5000) { lastLog = now; console.log(`[err] ${label}:`, e && (e.stack || e.message)); }
    }
  }, ms);
}

every(REGEN_MS, 'energy regen', () => {
  for (const c of clients.values()) {
    if (c.ready) c.energy = Math.min(ENERGY_MAX, c.energy + 1);
  }
});

// world simulation: monsters move, fight, respawn; depleted nodes come back
every(100, 'world tick', () => {
  const ps = ready().filter(c => !c.dead);
  if (!ps.length) return;
  const now = Date.now();
  const ev = world.tick(ps, now);

  for (const r of ev.revived) broadcastNode(r.map, r.x, r.y, r.kind, 1, 0);
  for (const m of ev.respawned) {
    for (const c of clients.values()) if (c.ready && c.map === m.map) c.send({ t: 'mon', id: m.id, kind: m.kind, x: m.x, y: m.y, hp: 1, maxHp: 1, spawn: true });
  }

  for (const h of ev.hits) {
    for (const c of clients.values()) {
      if (!c.ready || c.key !== h.key) continue;
      // worn armour soaks part of the blow, never below 1: being hit always costs.
      const dealt = Math.max(1, h.dmg - gearBonus(c.inv, 'armour'));
      c.hp -= dealt;
      if (c.hp <= 0) {
        c.hp = c.maxHp; c.dead = false;
        const sp = T.spawnPoint(c.map);
        c.x = sp.x; c.y = sp.y;
        c.sent.clear(); c.subs = new Set();
        stateSave(c);
        c.send({ t: 'died', by: h.name, spawn: sp, hp: c.hp, maxHp: c.maxHp });
        setView(c, c.x, c.y);
        console.log(`[net] ${c.name} was killed by ${h.name}`);
      } else {
        c.send({ t: 'dmg', dmg: dealt, by: h.name, hp: Math.round(c.hp), maxHp: c.maxHp });
      }
    }
  }
});

// presence + nearby monsters at 10Hz
every(100, 'presence tick', () => {
  const all = ready();
  if (!all.length) return;
  for (const c of all) {
    const near = [];
    for (const o of all) {
      if (o === c || o.map !== c.map) continue;
      if (Math.abs(o.x - c.x) > 72 || Math.abs(o.y - c.y) > 72) continue;
      near.push([o.key, o.name, Math.round(o.x * 10) / 10, Math.round(o.y * 10) / 10, o.hue]);
      if (near.length >= 64) break;
    }
    c.send({ t: 'players', list: near, you: [Math.round(c.x * 10) / 10, Math.round(c.y * 10) / 10, c.energy] });
    c.send({ t: 'mons', map: c.map, list: world.nearby(c.map, c.x, c.y) });
  }
});

every(5000, 'stats tick', () => {
  const n = live();
  if (!n) return;
  for (const c of clients.values()) {
    if (!c.ready) continue;
    c.send({ t: 'stats', claimed: countClaims(c.map), total: W * H, online: n, volatile: world.stats() });
  }
});

every(20000, 'state flush', () => {
  const now = Date.now();
  for (const c of clients.values()) if (c.ready && c.key) { qPlayLast.run(now, c.key); stateSave(c); }
});

// Idle sweep: sockets that have gone quiet are closed. This is what defeats slowloris —
// half-open connections cannot be parked here indefinitely. The read deadline is short
// before the handshake and generous after it, so a player who is simply standing still
// is never punished for it (the keepalive below keeps them counted as alive).
every(5000, 'idle sweep', () => {
  const now = Date.now();
  for (const c of [...clients.values()]) {
    if (c.gone) continue;
    if (now - c.lastRx > (c.ready ? IDLE_MS : HS_IDLE_MS)) dropClient(c, 'idle timeout');
  }
});

// WebSocket keepalive: browsers answer a ping frame themselves, so a "connected" client
// whose link has silently died stops looking alive within one ping interval.
every(WS_PING_MS, 'ws keepalive', () => {
  for (const c of clients.values()) {
    if (c.gone || !c.ready) continue;
    try { c.sock.write(wsEncode('', OP_PING)); } catch (e) {}
  }
});

// ---------- process safety net ---------------------------------------------
// One bad frame, one bad tick, one bad socket must never end the world. A shared
// persistent world that goes down is worse than any single fault, so these log loudly
// and keep serving.
process.on('uncaughtException', (e) => {
  try { console.log('[fatal] uncaughtException (still serving):', e && (e.stack || e.message)); } catch (_) {}
});
process.on('unhandledRejection', (r) => {
  try { console.log('[fatal] unhandledRejection (still serving):', (r && (r.stack || r.message)) || r); } catch (_) {}
});

// Test hook (see test-hardening.js): proves the net above really does keep the process
// serving after a fault. Never set in production.
if (process.env.STRATUM_TEST_THROW === '1') {
  setTimeout(() => { throw new Error('STRATUM_TEST_THROW: deliberate fault'); }, 700);
}

// ---------- shutdown -------------------------------------------------------
// Graceful: checkpoint every live player, say a proper goodbye on the wire, stop
// accepting, checkpoint the WAL and close SQLite before the process goes.
let shuttingDown = false;
function shutdown(sig) {
  if (shuttingDown) return;
  shuttingDown = true;
  console.log(`\n[world] ${sig} — sealing world…`);
  try { for (const c of clients.values()) if (c.ready && c.key) stateSave(c); }
  catch (e) { console.log('[err] shutdown state flush:', e && e.message); }
  try {
    for (const c of clients.values()) {
      try { c.sock.write(closeFrame(1001, 'server shutting down')); c.sock.end(); } catch (e) {}
    }
  } catch (e) {}
  try { server.close(); } catch (e) {}
  try { db.exec('PRAGMA wal_checkpoint(TRUNCATE)'); } catch (e) {}
  try { db.close(); }
  catch (e) { console.log('[err] db.close:', e && e.message); }
  try { process.exit(0); } catch (e) {}
}
process.on('SIGINT', () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));

server.listen(PORT, () => {
  console.log(`[world] STRATUM listening on http://127.0.0.1:${PORT}`);
  console.log(`[world] ${T.MAPS.length} maps, each ${W}x${H} = ${(W * H).toLocaleString()} tiles`);
  for (const m of T.MAPS) {
    const sp = T.spawnPoint(m.id);
    console.log(`[world]   #${m.id} ${m.name} (seed ${m.seed}) spawn ${sp.x},${sp.y} — ${m.desc}`);
  }
  console.log(`[volatile] ${JSON.stringify(world.stats())}`);
});
